String = "BANANA"
print(String[:])
print(String[1 : ])
print(String[2 : ])
print(String[3 : ])
print(String[4 : ])
print(String[5 : ])
print(String[ : 6])
print(String[ : 5])
print(String[ : 4])
print(String[ : 3])
print(String[ : 2])
print(String[ : 1])
print(String[2 : 7])
print(String[4 : -1])
print(String[-6 : -1])